"""tags table

Revision ID: 751986ee6788
Revises: e7ed5e014ace
Create Date: 2023-04-18 12:19:30.834957

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '751986ee6788'
down_revision = 'e7ed5e014ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_tags',
    sa.Column('notes', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notes'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tags'], ['tags.id'], )
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
