"""creating tables

Revision ID: 389968e03d21
Revises: 751986ee6788
Create Date: 2023-04-18 16:39:57.059012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389968e03d21'
down_revision = '751986ee6788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_tags', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_user", 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('note_tags', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
